//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTADM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiagramaEntidadesContainer : DbContext
    {
        public DiagramaEntidadesContainer()
            : base("name=DiagramaEntidadesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Objeto> Objetos { get; set; }
        public virtual DbSet<Entidade> Entidades { get; set; }
        public virtual DbSet<Raca> Racas { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<ModeloObjeto> ModelosObjeto { get; set; }
        public virtual DbSet<ModeloArea> ModeloAreaSet { get; set; }
    }
}
