//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTADM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidade
    {
        public int Id { get; set; }
        public int Vida { get; set; }
        public int Mana { get; set; }
        public int Estamina { get; set; }
        public int Moral { get; set; }
        public int Forca { get; set; }
        public int Inteligencia { get; set; }
        public int Destreza { get; set; }
        public string Genero { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Imagem { get; set; }
        public int RacaId { get; set; }
    
        public virtual Raca Raca { get; set; }
    }
}
