//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTADM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personagem : Entidade
    {
        public string Biografia { get; set; }
        public int AreaId { get; set; }
        public Nullable<int> ArmaPrincipalId { get; set; }
        public Nullable<int> ArmaId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Arma ArmaPrincipal { get; set; }
        public virtual Arma ArmaSecundaria { get; set; }
    }
}
